### ISSUE TITLE
Deprecated $IsOSX PowerShell Core Variable

### ISSUE THREAD

**Issue by iainbrighton** [it-praktyk/New-OutputObject#5]
In the PowerShell Core 6.0.0-beta7 the `$IsOSX` variable has been deprecated in favour of `$IsMacOS`. The `Test-CharsInPath` method needs updating accordingly.

**Comment by it-praktyk** [comment]
Thank you, corrected in the release [0.9.11](https://github.com/it-praktyk/New-OutputObject/releases/tag/0.9.11).
