### ISSUE TITLE
Set-StrictMode Compatibility

### ISSUE THREAD

**Issue by iainbrighton** [it-praktyk/New-OutputObject#6]
Is the `Test-CharsInPath` function the `$PSVersionTable.PSEdition` checks fail when strict mode is enabled. The bundled function in PScribo has been [updated like so](https://github.com/iainbrighton/PScribo/blob/dev/Src/Private/Test-CharsInPath.ps1#L103). This is passing checks on PS v3+ with strict mode enabled.

**Comment by it-praktyk** [comment]
Thank you, corrected in the release [0.9.11](https://github.com/it-praktyk/New-OutputObject/releases/tag/0.9.11).
